config/routes.rb
Rails.application.routes.draw do

  root to: 'restaurants#index', to: redirect('/restaurants')
  get 'restaurants' 			=> 'restaurants#index'

  get 'restaurants/new' 		=> 'restaurants#new'
  post 'submit_restaurant' 		=> 'restaurants#create_restaurant'

  get 'restaurants/:id' 		=> 'restaurants#review'

  get 'restaurants/:id/edit'  => 'restaurants#edit'
  post 'update_restaurant'    => 'restaurants#update_restaurant'

  get 'restaurants/:id/delete' 	=> 'restaurants#delete'

  get 'restaurants/:id/review' 	=> 'restaurants#new_review'
  post 'submit_review'			=> 'restaurants#submit_review'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :restaurant_reviews, dependent: :destroy

	validates :name, :cuisine_type, presence: true
  	validates :name, length: { minimum: 3 }
end

app/models/restaurant_review.rb
class RestaurantReview < ApplicationRecord
  	belongs_to :restaurant

  	validates :customer_name, :star_level, :description, presence: true
  	validates :customer_name, :description, length: { minimum: 3 }
  	validates :star_level, :inclusion => 1..5

  	def self.get_review(restaurant_id)
  		return RestaurantReview.where("restaurant_id =?", restaurant_id).order("star_level DESC")
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def create_restaurant
		if params[:process_type] == 'Cancel'
	        redirect_to '/restaurants'
	    elsif params[:process_type] == 'Register'
	       	@restaurant = Restaurant.new(restaurant_params)

	       	if @restaurant.save
	       		redirect_to '/restaurants', notice: "You have successfully registered a Restaurant!"
	       	else
	       		flash[:errors] = @restaurant.errors.full_messages
      			redirect_to '/restaurants/new'
	       	end
	    end
	end

	def update_restaurant
	    @restaurant = Restaurant.find(params[:restaurant_id])

	    if @restaurant.update(restaurant_params)
			redirect_to root_path, notice: "You have successfully updated a Dojo!"
	    else
			flash[:errors] = @restaurant.errors.full_messages
			redirect_to :controller => 'restaurants', :action => 'edit', id: params[:restaurant_id]
		end
	end

	def delete
	    Restaurant.find(params[:id]).destroy
	    redirect_to :root
	end

	def review
		@restaurant = Restaurant.find(params[:id])
		@restaurant_reviews = RestaurantReview.get_review(params[:id])
	end

	def new_review
		@restaurant = Restaurant.find(params[:id])
		@restaurant_review = RestaurantReview.new
	end

	def submit_review
		if params[:process_type] == 'Cancel'
	        redirect_to '/restaurants/'+restaurant_review_params[:restaurant_id].to_s
	    elsif params[:process_type] == 'Submit'

	       	@review = RestaurantReview.new(restaurant_review_params)

	       	if @review.save
	       		redirect_to :controller => 'restaurants', :action => 'review', id: restaurant_review_params[:restaurant_id]
	       	else
	       		flash[:errors] = @review.errors.full_messages
      			redirect_to :controller => 'restaurants', :action => 'new_review', id: restaurant_review_params[:restaurant_id]
	       	end
	    end
	end

	private
	    def restaurant_params
	      	params.require(:restaurant).permit(:name, :cuisine_type)
	    end

	    def restaurant_review_params
	      	params.require(:restaurant_review).permit(:restaurant_id,:customer_name, :star_level, :description)
	    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
  	<h1>Let's Eat</h1>

    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h3>Edit a restaurant</h3>

<div>
	<% if flash[:errors] %>
		<% flash[:errors].each do |e| %>
			<p><%= e %></p>
		<% end %>
	<% end %>
			
	<form action="/update_restaurant" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<input type="hidden" name="restaurant_id" value="<%= @restaurant.id %>">

		<p class="form-group">
			<label for="restaurant_name">Restaurant Name:</label>
			<input type="text" class="form-control" name="restaurant[name]" id="restaurant_name" value="<%= @restaurant.name %>">
			
		</p>
		<p class="form-group">
			<label for="restaurant_name">Cuisine:</label>
			<input type="text" class="form-control" name="restaurant[cuisine_type]" id="restaurant_name" value="<%= @restaurant.cuisine_type %>">
		</p>
		
		<input type="submit" value="Cancel" name="process_type" class="btn btn-default"/>
		<input type="submit" value="Update" name="process_type" class="btn btn-warning" />
	</form>
</div>

app/views/restaurants/index.html.erb
<%= button_to "New Restaurant", restaurants_new_path, {class: 'btn btn-info', method: :get} %>

<table class="table table-hover">
	<thead>
		<th>Restaurant</th>
		<th>Cuisine</th>
		<th>Actions Available</th>
	</thead>
	<tbody>
		<% if @restaurants.present? %>
			<%  @restaurants.each do |restaurant| %>
				<tr>
					<td><%= restaurant.name %></td>
					<td><%= restaurant.cuisine_type %></td>
					<td>
						<%= link_to  "Read reviews", {:controller => 'restaurants', :action => 'review', id: restaurant.id}, {class: 'btn btn-primary', method: :get} %>
						<%= link_to  "Update",  { :controller => 'restaurants', :action => 'edit', id: restaurant.id }, {class: 'btn btn-success', method: :get} %>
						<%= link_to  "Delete", { :controller => 'restaurants', :action => 'delete', id: restaurant.id }, {class: 'btn btn-danger',method: :get , :disabled => ((Time.parse(Time.now.utc.to_s) - Time.parse(restaurant.created_at.to_s)).to_i > 30) ? false : true} %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/restaurants/new.html.erb
<h3>Register a restaurant</h3>

<div>
	<% if flash[:errors] %>
		<% flash[:errors].each do |e| %>
			<p><%= e %></p>
		<% end %>
	<% end %>
			
	<form action="/submit_restaurant" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

		<p class="form-group">
			<label for="restaurant_name">Restaurant Name:</label>
			<input type="text" class="form-control" name="restaurant[name]" id="restaurant_name" value="<%= @restaurant.name %>">
			
		</p>
		<p class="form-group">
			<label for="restaurant_name">Cuisine:</label>
			<input type="text" class="form-control" name="restaurant[cuisine_type]" id="restaurant_name" value="<%= @restaurant.cuisine_type %>">
		</p>
		
		<input type="submit" value="Cancel" name="process_type" class="btn btn-default" />
		<input type="submit" value="Register" name="process_type" class="btn btn-warning"/>
	</form>
</div>

app/views/restaurants/new_review.html.erb
<h3>Write a review for <%= @restaurant.name %></h3>

<div>
	<% if flash[:errors] %>
		<% flash[:errors].each do |e| %>
			<p><%= e %></p>
		<% end %>
	<% end %>

	<form action="/submit_review" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<input type="hidden" name="restaurant_review[restaurant_id]" value="<%= @restaurant.id %>">

		<div class="form-group">
			<span>Your Name:</span>
			<label for="customer_name">
				<input type="text" class="form-control" name="restaurant_review[customer_name]" id="customer_name" value="<%= @restaurant_review.customer_name %>">
			</label>
		</div>
		<div class="form-group">
			<span>Stars:</span>
			<select class="form-control" name="restaurant_review[star_level]" id="star_level" value="<%= @restaurant_review.star_level %>">
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
				<option value="4">4</option>
				<option value="5">5</option>
			</select>
		</div>
		<div class="form-group">
			<label for="review_text">Your review:</label>
				<textarea class="form-control" name="restaurant_review[description]" id="review_text" cols="30" rows="10" value="<%= @restaurant_review.description %>"></textarea>
			
		</div>
		
		<input type="submit" value="Cancel" name="process_type" class="btn btn-default"/>
		<input type="submit" value="Submit" name="process_type" class="btn btn-warning"/>
	</form>
</div>

app/views/restaurants/restaurant_edit.html.erb
<h3>Edit a restaurant</h3>

<div>
	<form action="">
		<div>
			<span>Restaurant name:</span>
			<label for="restaurant_name">
				<input type="text" name="restaurant_name" id="restaurant_name">
			</label>
		</div>
		<div>
			<span>Cuisine type:</span>
			<label for="restaurant_name">
				<input type="text" name="restaurant_name" id="restaurant_name">
			</label>
		</div>
		
		<button>Cancel</button>
		<input type="submit" value="Edit">
	</form>
</div>

app/views/restaurants/review.html.erb
<h3> Review for <%= @restaurant.name %> </h3>

<%= link_to "New Review", { :controller => 'restaurants', :action => 'new_review', id: @restaurant.id }, {class: 'btn btn-info', method: :get} %>

<table class="table table-hover">
	<thead>
		<th>Customer</th>
		<th>Stars</th>
		<th>Description</th>
	</thead>
	<tbody>
		<% if @restaurant_reviews.present? %>
			<% @restaurant_reviews.each do |review| %>
				<tr>
					<td><%= review.customer_name.capitalize! %></td>
					<td><%= review.star_level %></td>
					<td><%= review.description %></td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>